server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: meditrack-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: meditrack-backend
          __path__: /workspace/backend/*/logs/*.log
      - targets:
          - localhost
        labels:
          job: meditrack-root
          __path__: /workspace/logs/*.log
