apiVersion: 1

datasources:
  - name: Zipkin
    uid: meditrack-zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: meditrack-loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
      spanBar:
        type: Duration
